# Generated by Django 2.1.3 on 2018-11-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orientador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(help_text='Requer 15 caracteres ou menos', max_length=15, unique=True, verbose_name='usuario')),
                ('password', models.CharField(help_text='Digite uma senha com 15 caracteres ou menos', max_length=15, verbose_name='senha')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('matricula', models.IntegerField()),
            ],
            options={
                'permissions': (('cadastrar tarefa', 'O usuario pode cadastrar tarefas'),),
            },
        ),
    ]
